### ISSUE TITLE
Agregar patron para no embed link ya definidos como ejemplo Youtube

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/curriculum-parser#16]

**Comment by lupomontero** [comment]
Gracias por el reportar esto @MaiaRojas 🎈 

Podrías porfa explicar un poco más a qué se refiere este issue? Cuál es el problema, cómo reproducirlo?

cc/ @ivandevp

**Comment by MaiaRojas** [comment]
Cuando el  autor de un curso quiere enlazar links  de lectura .
Ejm.
![screenshot from 2018-06-13 10-11-58](https://user-images.githubusercontent.com/25912510/41360382-4193166a-6ef2-11e8-9f38-483bcb550e2c.png)

Si este por ejemplo es un link de youtube, loom, etc
Se va embeber por defecto por el parser. 

La idea es que exista como un *tag*  o algo que haga que los links deseados no sean  embebidos.

**Comment by MaiaRojas** [comment]
Esto se puede solucionar cambiando la `url` del link con [Bitly](https://bitly.com/), para el parser no lo parsee.
Igual se mantiene el mismo contenido.
Es una sugerencia

**Comment by lupomontero** [comment]
Gracias por el update @MaiaRojas. De hecho justo estoy actualizando este repo y creo que esto es algo que podríamos agregar... te animas con una propuesta?

**Comment by lupomontero** [comment]
Cerrado en favor de #65
