### ISSUE TITLE
add new course summary tag

### ISSUE THREAD

**Issue by MaiaRojas** [Laboratoria/curriculum-parser#21]
Según la nueva UI.

![screenshot from 2018-06-13 11-03-50](https://user-images.githubusercontent.com/25912510/41363434-8386661a-6ef9-11e8-82af-d4afad842f19.png)

Se necesita  poder tener un pequeño resumen de max de 100 palabras.
Se penso crear un nuevo tag en  el parser para poder integrarlo en el LMS.

![screenshot from 2018-06-13 11-02-42](https://user-images.githubusercontent.com/25912510/41363390-60520e60-6ef9-11e8-9a89-c74eb5ff84d9.png)

cc/ @ivandevp

**Comment by lupomontero** [comment]
Hola @MaiaRojas, disculpa que nunca se llegó a atender este issue... :see_no_evil: 

Este cambio sigue siendo necesario?
