### ISSUE TITLE
Add "order" property to course structure

### ISSUE THREAD

**Issue by raulingg** [Laboratoria/curriculum-parser#26]
I'd like to add "order" property to course structure by default or pass it as an argument.

__How we use it__
The "order" property is used by LMS and Admission's webapps specifically in two places

- https://github.com/Laboratoria/lms.laboratoria.la/blob/bf7428323262d63423a569cf94a924c26c300c73/src/containers/cohort.jsx#L252

- https://github.com/Laboratoria/lms.laboratoria.la/blob/bf7428323262d63423a569cf94a924c26c300c73/src/components/cohort-course-add-dialog.jsx#L197

__current situation__
Right now, We need to add the "order" property manually, for instance in [this repo](https://github.com/Laboratoria/admission-curriculum/blob/master/README.md#2-edit-the-content)

Doing this manually will lead to undesired results if we make a mistake or forget doing it.

__How to reproduce the issue if course doesn't have order__
If courses don't have "order" property as part of their structures what happens in [this video](https://www.loom.com/share/86360775ae1d44508d2e52455222310f) :film_strip: 

/cc @lupomontero

**Comment by lupomontero** [comment]
Hi @raulingg,

Many thanks for raising this issue :+1: 

This is something that has been discussed in the past, and long time ago we decided that the `order` prop is something that does not really belong in the `course`/`topic` doc, and should probably be implemented as a separate feature in the context of the API/LMS and not the course docs themselves, as these are intended to be cohort independent. Let me explain why:

1. Courses/topics are parsed independently from one another, many of them living in completely different repos and managed by different people, ... and this point we do not necessarily know what cohorts will _use_ the couse or in what order it should appear within said cohorts (this affects both bootcamp and corporate training). In fact, we _dream_ with being able to show the _course catalogue_ in a way that does not suggest an order and rather would allow the user to sort or filter based on _tags_, _alphabetically_, _fields_ (computer science, javascript, ux, ...). Picture a _digital bookshelf_...

2. The _order_ would depend on the specific cohort, and as such we believe this should be handled separately from the parsing of the course, at which stage we do not know what the order should be (this is cohort dependent). As an example, the same `course` can be _added_ to many different _cohorts_, and the `order` is not necessarily the same in every cohort. Imagine you wanted to add a UX or L4B course to a bootcamp cohort (this is a real use case), and the given course has an order of `0` or `1`, the same as say the `javascript` course, this would mean that the newly added course would appear _first_, or at least before the other bootcamp related courses (`html`, `css`, `scm`, ...). In this case the resulting order would not be as desired and we would have no control over it, other than creating a cohort specific version of the course with a different `order`.

I would recommend adding a new data structure that would allow us to set the courses order within the context of a cohort, but not _globally_ as part of the course itself. For example, we could add the `order` prop in [`CohortTopicSchema`](https://github.com/Laboratoria/schemas/blob/develop/src/CohortTopicSchema.js), where we model the relationship between a course and cohort, but without affecting the course itself.

**Comment by raulingg** [comment]
> Hi @raulingg,
> 
> Many thanks for raising this issue 
> 
> This is something that has been discussed in the past, and long time ago we decided that the `order` prop is something that does not really belong in the `course`/`topic` doc, and should probably be implemented as a separate feature in the context of the API/LMS and not the course docs themselves, as these are intended to be cohort independent. Let me explain why:
> 
> 1. Courses/topics are parsed independently from one another, many of them living in completely different repos and managed by different people, ... and this point we do not necessarily know what cohorts will _use_ the couse or in what order it should appear within said cohorts (this affects both bootcamp and corporate training). In fact, we _dream_ with being able to show the _course catalogue_ in a way that does not suggest an order and rather would allow the user to sort or filter based on _tags_, _alphabetically_, _fields_ (computer science, javascript, ux, ...). Picture a _digital bookshelf_...
> 2. The _order_ would depend on the specific cohort, and as such we believe this should be handled separately from the parsing of the course, at which stage we do not know what the order should be (this is cohort dependent). As an example, the same `course` can be _added_ to many different _cohorts_, and the `order` is not necessarily the same in every cohort. Imagine you wanted to add a UX or L4B course to a bootcamp cohort (this is a real use case), and the given course has an order of `0` or `1`, the same as say the `javascript` course, this would mean that the newly added course would appear _first_, or at least before the other bootcamp related courses (`html`, `css`, `scm`, ...). In this case the resulting order would not be as desired and we would have no control over it, other than creating a cohort specific version of the course with a different `order`.
> 
> I would recommend adding a new data structure that would allow us to set the courses order within the context of a cohort, but not _globally_ as part of the course itself. For example, we could add the `order` prop in [`CohortTopicSchema`](https://github.com/Laboratoria/schemas/blob/develop/src/CohortTopicSchema.js), where we model the relationship between a course and cohort, but without affecting the course itself.

quite clear and precise. 

I have one doubt, I noted that we don't have "order" as a property of the course mongo-schema, we are not holding it in Mongo, are we? 

would you suggest sorting courses by other property different from "order"? which could be?

**Comment by lupomontero** [comment]
@raulingg, can you share your use case? If you have a small number of courses, and you know the order you want them in advance, you could do something like...

```js
// assuming you have an array of `courses` (retrieved from the database)
const sortedCourses = ['foo', 'bar', 'baz'].map(
  slug => courses.find(course => course.slug === slug),
);
```

**Comment by lupomontero** [comment]
@raulingg, any news on this?

**Comment by lupomontero** [comment]
Closing this issue in favour of https://github.com/Laboratoria/lms.laboratoria.la/pull/595
