### ISSUE TITLE
a4a885c made skills related tests to false positive

### ISSUE THREAD

**Issue by juanjordan** [Laboratoria/curriculum-parser#31]
Cuando se actualizó la parte de _assessments_ a opcional en a4a885c, se dejaron tests escritos que todavía pasan en cuanto la lógica solo valida cuando hay errores.

Dado que el código ya no hace `throw` cuando no se encuentran skills o se encuentran skills no identificados, los siguientes tests no llegan a la aserción en cuanto la lógica no entra al `.catch`. Por lo tanto el test pasa sin haber validado ninguna funcionalidad.

```js
it('should reject when no skills present')
it('should reject when unknown root skills category')
it('should reject when unknown skills category')
it('should reject when unknown skill')
```

Por un momento asumí que estos tests fueron dejados porque podríamos estar trabajando con versiones anteriores de la curricula donde sí deberíamos de validar la existencia de estas habilidades, pero aún así ese escenario me pareció extremo.

Mi propuesta es borrar estos tests y esperar que si en el futuro se vuelve a usar la lógica de skills (y esta cambia) se escriban otros tests. Mi única duda acá es si eso incluiría una actualización al MAJOR version.

No sé si me estoy perdiendo algún detalle (¿estamos haciendo snapshot testing?) y es por eso que dejo esta discusión por acá. 👀

**Comment by lupomontero** [comment]
Gracias por reportar esto @juanjordan :star: 

Después de revisar esto creo que solo uno de los tests parece _muerto_...

1. `should reject when no skills present` ya no tiene sentido... este lo estoy borrando en este momento...
2. `should reject when unknown root skills category` sigue teniendo [el comportamiento esperado](https://github.com/Laboratoria/curriculum-parser/blob/master/lib/project.js#L47).
3. `should reject when unknown skills category` también sigue siendo un [test válido](https://github.com/Laboratoria/curriculum-parser/blob/master/lib/project.js#L47)
4. `should reject when unknown skill` también sigue siendo un [test válido](https://github.com/Laboratoria/curriculum-parser/blob/master/lib/project.js#L69).

Por otro lado, todos estos tests tendremos que :wastebasket: una vez que reemplacemos la _rúbrica_ actual con los objetivos de aprendizaje...

cc/ @MaiaRojas
