### ISSUE TITLE
Parse and write down learning objectives to curriculum repo

### ISSUE THREAD

**Issue by juanjordan** [Laboratoria/curriculum-parser#32]
Ahora que vamos a usar la definición de objetivos de aprendizaje trabajado en https://github.com/Laboratoria/objetivos-de-aprendizaje, me parece deberíamos entender a este otro repo como la fuente de verdad con respecto a ese tema.

En ese supuesto, podríamos automatizar la forma en cómo se escribe la sección de objetivos de aprendizaje de cada proyecto, podríamos hacer un parse del contenido de ese repositorio y luego actualizar una copia local del repositorio de la currícula (Bootcamp) para poder hacer commit y push al remote.

De esta manera podríamos aplicar ciertas reglas de diseño y una forma de escribir estos listados previniendo inconsistencias que un script nos puede proveer.

Una primera pregunta es si esta funcionalidad debería existir en el `curriculum-parser` por ejemplo que corre cada vez que hay un merge al master de la curricula en sí.

Más allá del lugar donde exista esta funcionalidad ¿le ven el valor? cc: @lupomontero

**Comment by lupomontero** [comment]
Me tomo la libertad de cerrar este issue ya que esto ha sido reemplazado por https://github.com/Laboratoria/curriculum-parser/pull/39
