### ISSUE TITLE
Dependencia desactualizada `marked` arroja vulnerabilidad alta en repos asociados.

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/curriculum-parser#45]
Este repo usa [marked](https://www.npmjs.com/package/marked) como dependencia, la cual, al estar desactualizada, arroja una alta vulnerabilidad en otros proyectos en los cuales `curriculum-parser` es dependencia, como en el repo de [bootcamp](https://github.com/Laboratoria/bootcamp/).

Hay que revisar _breaking changes_ de nueva versión y actualizarlo acorde.

**Comment by lupomontero** [comment]
Esto ya está resuelto, `marked` está actualizado a `4.0.17`:

https://github.com/Laboratoria/curriculum-parser/blob/98fc31f469df3e1bee3732bd191a63208140f002/package.json#L21
