### ISSUE TITLE
Unificar proyectos en ES y PT para que tegan un identificador único

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/curriculum-parser#52]
Hoy en día los proyectos en ES y en PT están siendo parseados como objetos distintos.

Por ejemplo existe el proyecto `burger-queen-api-client` y también el proyecto `burger-queen-api-client-pt`.

Estos en realidad deberían ser sólo **un** objeto con el slug del proyecto `burger-queen-api-client` y que contenga algún atributo tipo `intl: [es-ES, pt-BR]` para poder diferenciar distintas versiones **del mismo proyecto**.

cc: @diegovelezg

**Comment by diegovelezg** [comment]
¿Estamos asumiendo que el identificador único es el slug?

**Comment by mfdebian** [comment]
sí! se refiere al atributo `slug`

**Comment by lupomontero** [comment]
Completado en #54 🚀
