### ISSUE TITLE
Unificar tópicos en ES y PT para que tegan un identificador único

### ISSUE THREAD

**Issue by mfdebian** [Laboratoria/curriculum-parser#53]
Hoy en día los tópicos en ES y en PT están siendo parseados como objetos distintos.

Por ejemplo existe el tópico `browser` y también el tópico `browser-pt`.

Estos en realidad deberían ser sólo un objeto con el slug del tópico `browser` y que contenga algún atributo tipo `intl: [es-ES, pt-BR]` para poder diferenciar distintas versiones del mismo tópico.

Además debe revisarse el objeto `topic` para ver si todos sus actuales atributos están siendo utilizados o tienen algún aporte de valor.

**Comment by lupomontero** [comment]
@mfdebian: me tomé la libertad de editar el título del issue. Decía _proyectos_ dónde creo que la intención era decir _tópicos_ :speak_no_evil:

**Comment by lupomontero** [comment]
Completado en #54 🚀
