### ISSUE TITLE
Agregar feature para transformar links de youtube, vimeo, etc

### ISSUE THREAD

**Issue by lupomontero** [Laboratoria/curriculum-parser#65]
En `v5.x` necesitamos todavía implementar el feature que analice y reemplace links a proveedores como YouTube, Vimeo, Loom, Google Slides, etc en el _body_ de los archivos markdown analizados. Este feature ya existe a día de hoy en la versión `v4.x`, pero todavía no se he implementado en el [PR de la rama `v5.x`](https://github.com/Laboratoria/curriculum-parser/pull/54).

En la versión actual el análisis de los links se hace usando JSDOM, pero en la nueva versión lo ideal sería que no necesitemos agregar JSDOM y que directamente trabajemos con [el árbol que produce el _parser_ de Markdown](https://github.com/Laboratoria/curriculum-parser/blob/161bd981d89d5f46d033313dbd9daef895a0560f/lib/common.js#L205) que estamos usando ahora.

Acá los `linkProviders` que soporta la versión actual de `curriculum-parser`:

https://github.com/Laboratoria/curriculum-parser/blob/941eab7e5ce9aa97f165f34c9f8253552c1a5dec/lib/common.js#L56

**Comment by unjust** [comment]
Estaba trabajando un poco en esto anoche. Para probar mi codigo, uso un test que llama `parseReadmes` con un argumento de directorio de fixtures. El detalles es `parseReadmes` [busca markdowns se llama `README` en si](https://github.com/Laboratoria/curriculum-parser/blob/v5.x/lib/common.js#L194), entonces tuve que renombrar uno de los `READMEs` en [los fixtures](https://github.com/Laboratoria/curriculum-parser/tree/v5.x/lib/__tests__/__fixtures__) (`README-with-youtube-short-link.md` -> `README.md`) 

Existe una mejor manera? Voy cambiando los fixtures para cada README suelto tiene un directorio (para todos pueden tener el nombre `README`), hasta que encuentro mejor manera.
